import { initNavScroll, initScrollToQuickStart, initSmoothAnchorLinks } from './modules/navigation.js';
import { initHeroParallax } from './modules/heroParallax.js';
import { initScrollReveal } from './modules/scrollReveal.js';
import { initTabs } from './modules/tabs.js';
import { initCopyCommand, initCopyLineButtons, initCopyStepButtons, initCodeCopyButtons } from './modules/clipboard.js';
import { initCardTilt } from './modules/cardTilt.js';
import { initArchitectureLayers } from './modules/architectureLayers.js';
import { initMobileNav } from './modules/mobileNav.js';
import { initReducedMotion } from './modules/reducedMotion.js';
import { initKonami } from './modules/konami.js';
import { initConsoleSignature } from './modules/consoleSignature.js';
import { initHeroBackground } from './three/heroBackground.js';

document.addEventListener('DOMContentLoaded', () => {
  initNavScroll();
  initScrollToQuickStart();
  initSmoothAnchorLinks();
  initHeroParallax();
  initScrollReveal();
  initTabs();
  initCopyCommand();
  initCopyLineButtons();
  initCopyStepButtons();
  initCodeCopyButtons();
  initCardTilt();
  initArchitectureLayers();
  initMobileNav();
  initReducedMotion();
  initKonami();
  initConsoleSignature();
  initHeroBackground();
});
